name: Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - run: yarn
        name: Resolve dependency
      - run: |
          git config --global user.email "mxcpy608@hotmail.com"
          git config --global user.name "Naoki Tomita"
        name: Setup git config for publish library.
      - run: yarn publish --new-version ${{ github.event.release.tag_name }}
        name: Release npmjs
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
